(* qatar Id: _________________________________ *)

(* ...
 * REQUIRES: ...
 * ENSURES:  ...
 *) 
fun pascal _ = raise Fail "Unimplemented"

(* ...
 * REQUIRES: ...
 * ENSURES:  ...
 *) 
fun exp _ = raise Fail "Unimplemented"
